images = {
	cursor : "sys",
	arrow : "sys",
	blackscreen : "sys",
	whitescreen : "sys",
	blank : "sys",
	speaker : "sys",
	cross : "sys",
	
	central : "bgs",
	omar : "bgs",
	outer : "bgs",
	testmap : "bgs",
	imperial : "bgs",
	
	chestanian_fortress : "planets",
	haufen1 : "planets",
	haufen2 : "planets",
	haufen3 : "planets",
	asteroid_asteroid1 : "planets",
	asteroid_asteroid2 : "planets",
	asteroid_asteroid3 : "planets",
	humania : "planets",
	pontes : "planets",
	quba : "planets",
	qubanian_colony : "planets",
	blank : "planets",
	testmoon : "planets",
	
	beam_ophianian : "projectiles",
	explosion : "projectiles",
	shot_light_1 : "projectiles",
	shot_medium_tripple : "projectiles",
	spikes_1 : "projectiles",
	emp_1 : "projectiles",
	emp_2 : "projectiles",
	triangle : "projectiles",
	testarrow : "projectiles",
	
	chestanian_colonizer : "ships",
	chestanian_spiketank : "ships",
	chestanian_glider : "ships",
	chestanian_quintalglider : "ships",
	birchanian_glider : "ships",
	cylon_basestar : "ships",
	helon_baseship_mkii : "ships",
	helon_raider_mkiii : "ships",
	humanian_protobaseship_helonia : "ships",
	humanian_shuttle : "ships",
	humanian_satalite : "ships",
	none_fatman : "ships",
	none_testarrow : "ships",
	ophianic_annector : "ships",
	ophianic_chunk : "ships",
	tonium_chunk : "ships",
	qubanian_colonizer : "ships",
	qubanian_colonizer_mkii : "ships",
	republic_hq : "ships",
	samus_ship : "ships",
}



audibles = [
	"theme1",
	"shot_1",
	"shot_2",
	"hit_1",
	"hit_2",
	"bounce_1",
	"theme_central",
	"theme_omar",
	"explosion1"
]