var resources = {
    "blank": "ress/blank.png",
    "whitescreen": "ress/whitescreen.png",
    "blackscreen": "ress/blackscreen.png",
    "basestar": "ress/ships/sprite_basestar.png",
    "black": "ress/black.png",
	"cursor" : "ress/cursor.png",
	"explosion" : "ress/projectiles/explosion.png",
	"testarrow" : "ress/ships/testarrow.png",
	"testmap" : "ress/bgs/testmap.png",
	"central_sector" : "ress/bgs/central.png",
	"shot_1" : "ress/projectiles/shot_1.png",
	"shot_1_tripple" : "ress/projectiles/shot_1_tripple.png",
	"rep_hq" : "ress/ships/rep hq.png",
	"humanian_shuttle" : "ress/ships/humanian shuttle.png",
	"protobaseship_helonia" : "ress/ships/protobaseship helonia.png",
	"fat dude" : "ress/ships/fatman.png",
	"testMoon" : "ress/planets/test.png",
	"humania" : "ress/planets/humania.png",
	"qubanic colonizer" : "ress/ships/qubanic colonizer.png",
	"ophianian annector-star" : "ress/ships/ophianic annector-star.png",
	"ophianian chunk" : "ress/ships/ophianic chunk.png",
	"beam_ophianian_h" : "ress/projectiles/ophianian beam.png",
	"pontes" : "ress/planets/pontes.png",
	"humanian_satalite" : "ress/ships/humanian satalite.png",
	"haufen" : "ress/planets/haufen.png",
}
