var resources = {
    "blank": "ress/blank.png",
    "whitescreen": "ress/whitescreen.png",
    "blackscreen": "ress/blackscreen.png",
    "basestar": "ress/ships/sprite_basestar.png",
    "black": "ress/black.png",
	"cursor" : "ress/cursor.png",
	"explosion" : "ress/projectiles/explosion.png",
	"testarrow" : "ress/ships/testarrow.png",
	"testmap" : "ress/bgs/testmap.png",
	"central_sector" : "ress/bgs/central.png",
	"shot_light1" : "ress/projectiles/shot_light1.png",
	"shot_light_tripple" : "ress/projectiles/shot_light_tripple.png",
	"rep_hq" : "ress/ships/rep hq.png",
	"humanian_shuttle" : "ress/ships/humanian shuttle.png",
	"protobaseship_helonia" : "ress/ships/protobaseship helonia.png",
	"fat dude" : "ress/ships/fatman.png",
	"testMoon" : "ress/planets/test.png",
	"humania" : "ress/planets/humania.png",
	"qubanic colonizer" : "ress/ships/qubanic colonizer.png",
}
