var image_ref =		//Only use "\" to break lines or seperate arguments!
	"cursor\
	arrow\
	blackscreen\
	whitescreen\
	blank\
	speaker\
	cross\
	\
	\
	bg_outer\
	bg_omar\
	bg_testmap\
	bg_imperial\
	bg_imperial2\
	bg_central\
	\
	planet_asteroid_asteroid1\
	planet_asteroid_asteroid2\
	planet_asteroid_asteroid3\
	planet_birchanian_fortress\
	planet_blank\
	planet_chestanian_fortress\
	planet_haufen1\
	planet_haufen2\
	planet_haufen3\
	planet_humania\
	planet_pontes\
	planet_quba\
	planet_testmoon\
	\
	proj_beam_ophianian\
	proj_beam_star\
	proj_emp1\
	proj_emp2\
	proj_explosion\
	proj_shot_light1\
	proj_shot_medium_tripple\
	proj_shot_medium1\
	proj_spikes1\
	proj_triangle\
	\
	ship_birchanian_glider\
	ship_chestanian_colonizer\
	ship_chestanian_glider\
	ship_chestanian_quintglider\
	ship_chestanian_spiketank\
	ship_helon_baseship_mkii\
	ship_helon_raider_mkiii\
	ship_humanian_protobaseship_helonia\
	ship_humanian_satalite\
	ship_humanian_shuttle\
	ship_none_fatman\
	ship_none_testarrow\
	ship_ophianian_annector\
	ship_ophianian_chunk\
	ship_qubanian_colonizer\
	ship_qubanian_colonizer_mkii\
	ship_qubanian_colony\
	ship_republic_hq\
	ship_tonium_chunk\
	ship_tonium_star\
	"
;